services:
  # -------------------------
  # Core Infrastructure
  # -------------------------
  redis:
    image: redis:7-alpine
    container_name: vigil_redis
    ports:
      - "6380:6379"

  postgres:
    image: postgres:15-alpine
    container_name: vigil_postgres
    environment:
      POSTGRES_USER: vigil
      POSTGRES_PASSWORD: vigilpass
      POSTGRES_DB: vigil
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # -------------------------
  # Python API (Collector + Policy Engine)
  # -------------------------
  api:
    image: python:3.12-slim
    container_name: vigil_api
    working_dir: /app
    volumes:
      - ./python:/app
      - ./configs:/app/configs
      - ./manifests:/app/manifests
    environment:
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgresql+asyncpg://vigil:vigilpass@postgres:5432/vigil
      REDIS_URL: redis://redis:6379/0
      CONFIG_PATH: /app/configs/collector.yaml
    command: >
      sh -c "
        pip install --no-cache-dir fastapi uvicorn redis psycopg2-binary asyncpg pyyaml python-dotenv requests pydantic-settings sqlalchemy &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  # -------------------------
  # Go GitOps Daemon
  # -------------------------
  gitopsd:
    image: golang:1.22
    container_name: vigil_gitopsd
    working_dir: /workspace/go
    volumes:
      - ./go:/workspace/go
      - ./configs:/workspace/configs
      - ./manifests:/workspace/manifests
    environment:
      GITOPSD_COLLECTOR_URL: http://api:8000/api/v1/actions
    command: >
      sh -c "
        go mod tidy &&
        go run ./gitopsd/cmd/gitopsd
      "
    depends_on:
      - api
      - redis

  # -------------------------
  # Go Agent (Metrics Producer)
  # -------------------------
  agent:
    image: golang:1.22
    container_name: vigil_agent
    working_dir: /workspace/go
    volumes:
      - ./go:/workspace/go
      - ./configs:/workspace/configs
    environment:
      API_HOST: api
      API_PORT: "8000"
    command: >
      sh -c "
        go mod tidy &&
        go run ./agent/cmd/agent
      "
    depends_on:
      - api
      - redis

  # -------------------------
  # Go Remediator
  # -------------------------
  remediator:
    image: golang:1.22
    container_name: vigil_remediator
    working_dir: /workspace/go
    volumes:
      - ./go:/workspace/go
      - ./configs:/workspace/configs
    environment:
      API_HOST: api
      API_PORT: "8000"
    command: >
      sh -c "
        go mod tidy &&
        go run ./remediator/cmd/remediator
      "
    depends_on:
      - api
      - redis

# -------------------------
# Volumes
# -------------------------
volumes:
  pg_data:
